version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    expose:
      - 5432
    environment:
      - POSTGRES_USER=espdb_user
      - POSTGRES_PASSWORD=espdb_pass
      - POSTGRES_DB=espcd_backend
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: unless-stopped
    expose:
      - 6379

  app:
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - ESPCD_BACKEND_DATABASE_URL=postgres://espdb_user:espdb_pass@postgres/espcd_backend
      - REDIS_URL=redis://redis:6379/1
      - SECRET_KEY_BASE=secret-key-base
    volumes:
      - storage:/app/storage
    command: sh -c "rake db:create && rake db:migrate && rails s -b 0.0.0.0"
    depends_on:
      - postgres
      - redis

volumes:
  postgres:
  storage:
