version: '3'

services:
  postgres:
    image: postgres:alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=espdb_user
      - POSTGRES_PASSWORD=espdb_pass
      - POSTGRES_DB=espcd_backend

  app:
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - ESPCD_BACKEND_DATABASE_URL=postgres://espdb_user:espdb_pass@postgres/espcd_backend
    command: sh -c "rake db:create && rake db:migrate && rails s -b 0.0.0.0"
    depends_on:
      - postgres
